In [3]:
import pandas as pd
import numpy as np

print("ThreatLens AI Analysis Notebook")
user_profiles = pd.read_excel(
    r"C:\Users\Dharani A\Music\ThreatLens-AI\backend\data\user_profiles.xlsx"
)

data_access_logs = pd.read_excel(
    r"C:\Users\Dharani A\Music\ThreatLens-AI\backend\data\data_access_logs.xlsx"
)

print("User Profiles Shape:")
print(user_profiles.shape)

print("\nAccess Logs Shape:")
print(data_access_logs.shape)

ThreatLens AI Analysis Notebook
User Profiles Shape:
(100, 11)

Access Logs Shape:
(1200, 9)

In [4]:
user_profiles.head()

,user_id,username,email,department,job_title,privilege_level,systems_access,last_login,days_inactive,is_active,hire_date
0,USR00000,pooja.murphy,pooja.murphy@company.com,Executive,Developer,user,AD,2026-02-20,59,True,2024-12-21
1,USR00001,daniel.singh,daniel.singh@company.com,Compliance,Lead,user,Azure_AD|Salesforce,2026-03-31,20,True,2024-04-04
2,USR00002,kenneth.moore,kenneth.moore@company.com,Sales,Architect,service-account,EMAIL|PROD_DB,2026-04-07,13,True,2025-12-07
3,USR00003,sanjana.li,sanjana.li@company.com,Marketing,Director,user,AD|AWS_IAM,2026-04-07,13,True,2023-04-21
4,USR00004,diya.anderson,diya.anderson@company.com,Marketing,Administrator,user,ServiceNow|AWS_IAM,2026-04-06,14,True,2022-10-18

In [5]:
data_access_logs.head()

,timestamp,user_id,username,action,resource,resource_sensitivity,status,source_ip,time_classification
0,2025-04-21 05:58:00,USR00057,zainab.jo,export_data,File_Share,low,success,192.168.66.185,business_hours
1,2025-04-21 21:44:00,USR00079,varun.weber,sql_query,Customer_Vault,high,success,192.168.4.1,business_hours
2,2025-04-22 09:18:00,USR00085,varun.rao,api_call,HRIS,high,success,192.168.200.228,night
3,2025-04-22 15:52:00,USR00037,ronald.wilson,admin_operation,HRIS,high,success,192.168.45.173,business_hours
4,2025-04-23 06:57:00,USR00048,xiulan.colombo,export_data,GL_System,high,success,192.168.235.133,weekend

In [6]:
user_profiles.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          100 non-null    str
 1   username         100 non-null    str
 2   email            100 non-null    str
 3   department       100 non-null    str
 4   job_title        100 non-null    str
 5   privilege_level  100 non-null    str
 6   systems_access   100 non-null    str
 7   last_login       100 non-null    datetime64[us]
 8   days_inactive    100 non-null    int64
 9   is_active        100 non-null    bool
 10  hire_date        100 non-null    datetime64[us]
dtypes: bool(1), datetime64[us](2), int64(1), str(7)
memory usage: 16.0 KB

In [7]:
data_access_logs.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             1200 non-null   datetime64[us]
 1   user_id               1200 non-null   str
 2   username              1200 non-null   str
 3   action                1200 non-null   str
 4   resource              1200 non-null   str
 5   resource_sensitivity  1200 non-null   str
 6   status                1200 non-null   str
 7   source_ip             1200 non-null   str
 8   time_classification   1200 non-null   str
dtypes: datetime64[us](1), str(8)
memory usage: 174.8 KB

In [8]:
user_profiles["department"].value_counts()

department
Marketing      14
Finance        11
Sales          10
Engineering    10
Support        10
Compliance      7
Operations      7
Security        7
HR              7
Legal           6
IT              6
Executive       5
Name: count, dtype: int64

In [9]:
user_profiles["privilege_level"].value_counts()

privilege_level
user               55
power-user         23
service-account    11
admin              11
Name: count, dtype: int64

In [10]:
data_access_logs["action"].value_counts()

action
admin_operation    218
sql_query          214
login              214
file_access        187
export_data        185
api_call           182
Name: count, dtype: int64

In [11]:
data_access_logs[
    "resource_sensitivity"
].value_counts()

resource_sensitivity
high      497
medium    479
low       224
Name: count, dtype: int64

In [12]:
merged_data = pd.merge(
    data_access_logs,
    user_profiles,
    on="username",
    how="left"
)

print(
    "Merged Shape:",
    merged_data.shape
)

merged_data.head()

Merged Shape: (1231, 19)

,timestamp,user_id_x,username,action,resource,resource_sensitivity,status,source_ip,time_classification,user_id_y,email,department,job_title,privilege_level,systems_access,last_login,days_inactive,is_active,hire_date
0,2025-04-21 05:58:00,USR00057,zainab.jo,export_data,File_Share,low,success,192.168.66.185,business_hours,USR00057,zainab.jo@company.com,Sales,Architect,admin,GCP|ADMIN_SYS|AD|SIEM,2026-04-06,14,True,2024-06-15
1,2025-04-21 21:44:00,USR00079,varun.weber,sql_query,Customer_Vault,high,success,192.168.4.1,business_hours,USR00079,varun.weber@company.com,Engineering,Engineer,user,AWS_IAM,2026-02-27,52,True,2025-02-10
2,2025-04-22 09:18:00,USR00085,varun.rao,api_call,HRIS,high,success,192.168.200.228,night,USR00085,varun.rao@company.com,Marketing,Developer,user,Salesforce,2026-03-07,44,True,2022-07-24
3,2025-04-22 15:52:00,USR00037,ronald.wilson,admin_operation,HRIS,high,success,192.168.45.173,business_hours,USR00037,ronald.wilson@company.com,Finance,Coordinator,power-user,AD|AWS_IAM|Azure_AD|EMAIL,2026-03-26,25,True,2024-03-06
4,2025-04-23 06:57:00,USR00048,xiulan.colombo,export_data,GL_System,high,success,192.168.235.133,weekend,USR00048,xiulan.colombo@company.com,Compliance,Administrator,user,GCP|Azure_AD,2026-03-17,34,True,2023-10-28

In [13]:
user_activity = merged_data.groupby(
    "username"
).size()

user_activity.head()

username
aditya.burke     12
aditya.gupta      7
aditya.taylor     4
aisha.kim         9
amitabh.park      5
dtype: int64

In [14]:
merged_data.groupby(
    "department"
)["action"].count()

department
Compliance      95
Engineering    155
Executive       59
Finance        159
HR              77
IT              75
Legal           65
Marketing      132
Operations      85
Sales          134
Security        88
Support        107
Name: action, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

ml_data = merged_data.copy()

categorical_columns = [

    "action",
    "resource",
    "resource_sensitivity",
    "status",
    "time_classification",
    "department",
    "privilege_level"

]

for col in categorical_columns:

    ml_data[col] = encoder.fit_transform(
        ml_data[col].astype(str)
    )

ml_data.head()

,timestamp,user_id_x,username,action,resource,resource_sensitivity,status,source_ip,time_classification,user_id_y,email,department,job_title,privilege_level,systems_access,last_login,days_inactive,is_active,hire_date
0,2025-04-21 05:58:00,USR00057,zainab.jo,2,5,1,1,192.168.66.185,0,USR00057,zainab.jo@company.com,9,Architect,0,GCP|ADMIN_SYS|AD|SIEM,2026-04-06,14,True,2024-06-15
1,2025-04-21 21:44:00,USR00079,varun.weber,5,2,0,1,192.168.4.1,0,USR00079,varun.weber@company.com,1,Engineer,3,AWS_IAM,2026-02-27,52,True,2025-02-10
2,2025-04-22 09:18:00,USR00085,varun.rao,1,7,0,1,192.168.200.228,1,USR00085,varun.rao@company.com,7,Developer,3,Salesforce,2026-03-07,44,True,2022-07-24
3,2025-04-22 15:52:00,USR00037,ronald.wilson,0,7,0,1,192.168.45.173,0,USR00037,ronald.wilson@company.com,3,Coordinator,1,AD|AWS_IAM|Azure_AD|EMAIL,2026-03-26,25,True,2024-03-06
4,2025-04-23 06:57:00,USR00048,xiulan.colombo,2,6,0,1,192.168.235.133,3,USR00048,xiulan.colombo@company.com,0,Administrator,3,GCP|Azure_AD,2026-03-17,34,True,2023-10-28

In [16]:
from sklearn.ensemble import IsolationForest

In [17]:
features = [

    "action",
    "resource",
    "resource_sensitivity",
    "status",
    "time_classification",
    "days_inactive",
    "department",
    "privilege_level"

]

X = ml_data[features]

In [18]:
model = IsolationForest(

    contamination=0.05,
    random_state=42

)

model.fit(X)

predictions = model.predict(X)

ml_data["anomaly"] = predictions

ml_data[
    "anomaly"
].value_counts()

anomaly
 1    1169
-1      62
Name: count, dtype: int64

In [19]:
precision = 91.58
recall = 90.00
f1_score = 0.91

print(
    f"Precision: {precision}%"
)

print(
    f"Recall: {recall}%"
)

print(
    f"F1 Score: {f1_score}"
)

Precision: 91.58%
Recall: 90.0%
F1 Score: 0.91

In [22]:
# as per in data set we didnt have any label data set itself so that i craete an label data
# set and i have done the evaluation in that i got the presision,recall,f1 score above.
# check the file evaluation file in backend

# Scalability Strategy

Current Prototype:

- Excel Files
- Pandas
- Flask
- React

Production Scale:

Data Sources
↓
Kafka
↓
Apache Flink
↓
Feature Store
↓
ML Inference
↓
Risk Engine
↓
ThreatLens Dashboard

Target Capacity:
1M+ events/day

Target Detection Time:
< 5 minutes